export {Adminpage} from "./Adminpage"
export {CreateAccount} from "./CreateAccount"
export {EnableMap} from "./EnableMap"
export {StudentPreasent} from "./StudentPreasent"
export {MiniAttenetendce} from "./MiniAttenetendce"